name: Tests/BuildAndDeployToVDS

on:
  push:
    branches: [ "main" ]

jobs:
  asp-api_unit-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Клонируем репозиторий
      uses: actions/checkout@v6

    - name: Установка .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Скачивание приблуд
      run: dotnet restore

    - name: Виновник торжества
      run: dotnet test GMServerWebPanel.API.UnitTests

  asp-api_integration-tests:
    runs-on: ubuntu-latest
    needs: asp-api_unit-tests
    
    steps:
    - name: Клонируем репозиторий
      uses: actions/checkout@v6

    - name: Установка .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Скачивание приблуд
      run: dotnet restore

    - name: Виновник торжества
      run: dotnet test GMServerWebPanel.API.IntegrationTests

  shared-folder:
    runs-on: ubuntu-latest
    needs: [asp-api_unit-tests, asp-api_integration-tests]

    steps:
    - name: Создание общих папок
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VDS_HOST }}
        username: ${{ secrets.VDS_USER }}
        key: ${{ secrets.VDS_SSH_KEY }}
        script: |
          mkdir /var/www/GMServerWebPanel
          mkdir /var/www/GMServerWebPanel/api
          mkdir /var/www/GMServerWebPanel/frontend

  build-api-deploy:
    runs-on: ubuntu-latest
    needs: [asp-api_unit-tests, asp-api_integration-tests, shared-folder]

    steps:
    - name: Клонируем репозиторий
      uses: actions/checkout@v6

    - name: Установка .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Скачивание приблуд
      run: dotnet restore

    - name: Стройка
      run: dotnet build --no-restore

    - name: Стройка полноценная
      run: |
        dotnet publish GMServerWebPanel.API/GMServerWebPanel.API.csproj \
          -c Release \
          -r linux-x64 \
          -o ./publish \
          --self-contained true

    - name: Выключаем сервис, очищаем папку проекта
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VDS_HOST }}
        username: ${{ secrets.VDS_USER }}
        key: ${{ secrets.VDS_SSH_KEY }}
        script: |
          sudo systemctl stop GMServerWebPanel || true
          rm -rf /var/www/GMServerWebPanel/api/*
    
    - name: Выкладка на VDS
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.VDS_HOST }}
        username: ${{ secrets.VDS_USER }}
        key: ${{ secrets.VDS_SSH_KEY }}
        source: "./publish/*"
        target: "/var/www/GMServerWebPanel/api"
        strip_components: 1
        overwrite: true

  build-react-deploy:
    runs-on: ubuntu-latest
    needs: [asp-api_unit-tests, asp-api_integration-tests, shared-folder]

    steps:
    - name: Клонируем репозиторий
      uses: actions/checkout@v6

    - name: Setup Node
      uses: actions/setup-node@v5
      with:
        node-version: '24.x'

    - name: Install dependencies
      run: npm install
      working-directory: ./GMServerWebPanel.React

    - name: Build React app
      run: npm run build
      working-directory: ./GMServerWebPanel.React

    - name: Удаление старого содержимого
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VDS_HOST }}
        username: ${{ secrets.VDS_USER }}
        key: ${{ secrets.VDS_SSH_KEY }}
        script: |
          rm -rf /var/www/GMServerWebPanel/frontend/*

    - name: Выкладка на VDS
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.VDS_HOST }}
        username: ${{ secrets.VDS_USER }}
        key: ${{ secrets.VDS_SSH_KEY }}
        source: "./GMServerWebPanel.React/dist/*"
        target: "/var/www/GMServerWebPanel/frontend"
        strip_components: 2
        overwrite: true

  start-services:
    runs-on: ubuntu-latest
    needs: [build-api-deploy, build-react-deploy]

    steps:
    - name: Запуск сервисов
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VDS_HOST }}
        username: ${{ secrets.VDS_USER }}
        key: ${{ secrets.VDS_SSH_KEY }}
        script: |
          sudo systemctl start GMServerWebPanel
          sudo systemctl restart nginx
