name: Tests/BuildAndDeployToVDS

on:
  push:
    branches: [ "main" ]

jobs:
  asp-api_unit-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Клонируем репозиторий
      uses: actions/checkout@v4

    - name: Установка .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Скачивание приблуд
      run: dotnet restore

    - name: Виновник торжества
      run: dotnet test GMServerWebPanel.API.UnitTests

    asp-api_integration-tests:
      runs-on: ubuntu-latest
      needs: asp-api_unit-tests
    
    steps:
    - name: Клонируем репозиторий
      uses: actions/checkout@v4

    - name: Установка .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Скачивание приблуд
      run: dotnet restore

    - name: Виновник торжества
      run: dotnet test GMServerWebPanel.API.IntegrationTests

  build-api-deploy:
    runs-on: ubuntu-latest
    needs: [asp-api_unit-tests, asp-api_integration-tests]

    steps:
    - name: Клонируем репозиторий
      uses: actions/checkout@v4

    - name: Установка .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Скачивание приблуд
      run: dotnet restore

    - name: Стройка
      run: dotnet build --no-restore

    - name: Стройка полноценная
      run: |
        dotnet publish GMServerWebPanel.API/GMServerWebPanel.API.csproj \
          -c Release \
          -r linux-x64 \
          -o ./publish \
          -sc

    - name: Выключаем сервис, очищаем папку проекта
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VDS_HOST }}
        username: ${{ secrets.VDS_USER }}
        key: ${{ secrets.VDS_SSH_KEY }}
        script: |
          sudo systemctl stop GmodServerWebPanel || true
          cd /var/www/GmodServerWebPanel
          shopt -s extglob
          # Удаляем всё, кроме фронта, он загружается отдельно.
          rm -rf !(wwwroot)
    
    - name: Выкладка на VDS
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.VDS_HOST }}
        username: ${{ secrets.VDS_USER }}
        key: ${{ secrets.VDS_SSH_KEY }}
        source: "./publish/*"
        target: "/var/www/GmodServerWebPanel"
        strip_components: 1
        overwrite: true
    
    - name: Restart application
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VDS_HOST }}
        username: ${{ secrets.VDS_USER }}
        key: ${{ secrets.VDS_SSH_KEY }}
        script: |
          # Запускаем приложение
          sudo systemctl start GmodServerWebPanel
          sudo systemctl restart nginx

  build-react-deploy:
    runs-on: ubuntu-latest
    needs: [asp-api_unit-tests, asp-api_integration-tests]

    steps:
    - name: Клонируем репозиторий
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '24.x'

    - name: Install dependencies
      run: npm install
      working-directory: ./GMServerWebPanel.React

    - name: Build React app
      run: npm run build
      working-directory: ./GMServerWebPanel.React

    - name: Удаление старого содержимого wwwroot
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VDS_HOST }}
        username: ${{ secrets.VDS_USER }}
        key: ${{ secrets.VDS_SSH_KEY }}
        script: |
          rm -rf /var/www/GmodServerWebPanel/wwwroot/*

    - name: Выкладка на VDS
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.VDS_HOST }}
        username: ${{ secrets.VDS_USER }}
        key: ${{ secrets.VDS_SSH_KEY }}
        source: "./GMServerWebPanel.React/dist/*"
        target: "/var/www/GmodServerWebPanel/wwwroot"
        strip_components: 2
        overwrite: true